INSERT INTO [Aplicacion_Productos].[dbo].[Articulos] values('agua','2,000',(SELECT * FROM OPENROWSET(BULK 'C:\Bulk\Progra trabajo\agua\1.jpg', SINGLE_BLOB) as T1),'super1','Productos Alimenticios')
INSERT INTO [Aplicacion_Productos].[dbo].[Articulos] values('agua','2,000',(SELECT * FROM OPENROWSET(BULK 'C:\Bulk\Progra trabajo\agua\2.jpg', SINGLE_BLOB) as T1),'super1','Productos Alimenticios')
INSERT INTO [Aplicacion_Productos].[dbo].[Articulos] values('agua','2,000',(SELECT * FROM OPENROWSET(BULK 'C:\Bulk\Progra trabajo\agua\3.jpg', SINGLE_BLOB) as T1),'super1','Productos Alimenticios')
INSERT INTO [Aplicacion_Productos].[dbo].[Articulos] values('agua','2,000',(SELECT * FROM OPENROWSET(BULK 'C:\Bulk\Progra trabajo\agua\4.jpg', SINGLE_BLOB) as T1),'super1','Productos Alimenticios')
INSERT INTO [Aplicacion_Productos].[dbo].[Articulos] values('agua','2,000',(SELECT * FROM OPENROWSET(BULK 'C:\Bulk\Progra trabajo\agua\5.jpg', SINGLE_BLOB) as T1),'super1','Productos Alimenticios')
INSERT INTO [Aplicacion_Productos].[dbo].[Articulos] values('agua','2,000',(SELECT * FROM OPENROWSET(BULK 'C:\Bulk\Progra trabajo\agua\6.jpg', SINGLE_BLOB) as T1),'super1','Productos Alimenticios')
INSERT INTO [Aplicacion_Productos].[dbo].[Articulos] values('ejemplo','2,000',(SELECT * FROM OPENROWSET(BULK 'C:\Bulk\Progra trabajo\arroz\1.jpg', SINGLE_BLOB) as T1),'super1','Productos Alimenticios')
INSERT INTO [Aplicacion_Productos].[dbo].[Articulos] values('ejemplo','2,000',(SELECT * FROM OPENROWSET(BULK 'C:\Bulk\Progra trabajo\arroz\2.jpg', SINGLE_BLOB) as T1),'super1','Productos Alimenticios')
INSERT INTO [Aplicacion_Productos].[dbo].[Articulos] values('ejemplo','2,000',(SELECT * FROM OPENROWSET(BULK 'C:\Bulk\Progra trabajo\arroz\3.jpg', SINGLE_BLOB) as T1),'super1','Productos Alimenticios')
INSERT INTO [Aplicacion_Productos].[dbo].[Articulos] values('ejemplo','2,000',(SELECT * FROM OPENROWSET(BULK 'C:\Bulk\Progra trabajo\arroz\4.jpg', SINGLE_BLOB) as T1),'super1','Productos Alimenticios')
INSERT INTO [Aplicacion_Productos].[dbo].[Articulos] values('ejemplo','2,000',(SELECT * FROM OPENROWSET(BULK 'C:\Bulk\Progra trabajo\arroz\5.jpg', SINGLE_BLOB) as T1),'super1','Productos Alimenticios')
INSERT INTO [Aplicacion_Productos].[dbo].[Articulos] values('ejemplo','2,000',(SELECT * FROM OPENROWSET(BULK 'C:\Bulk\Progra trabajo\arroz\6.jpg', SINGLE_BLOB) as T1),'super1','Productos Alimenticios')
INSERT INTO [Aplicacion_Productos].[dbo].[Articulos] values('ejemplo','2,000',(SELECT * FROM OPENROWSET(BULK 'C:\Bulk\Progra trabajo\azucar\1.jpg', SINGLE_BLOB) as T1),'super1','Productos Alimenticios')
INSERT INTO [Aplicacion_Productos].[dbo].[Articulos] values('ejemplo','2,000',(SELECT * FROM OPENROWSET(BULK 'C:\Bulk\Progra trabajo\azucar\2.jpg', SINGLE_BLOB) as T1),'super1','Productos Alimenticios')
INSERT INTO [Aplicacion_Productos].[dbo].[Articulos] values('ejemplo','2,000',(SELECT * FROM OPENROWSET(BULK 'C:\Bulk\Progra trabajo\azucar\3.jpg', SINGLE_BLOB) as T1),'super1','Productos Alimenticios')
INSERT INTO [Aplicacion_Productos].[dbo].[Articulos] values('ejemplo','2,000',(SELECT * FROM OPENROWSET(BULK 'C:\Bulk\Progra trabajo\azucar\4.jpg', SINGLE_BLOB) as T1),'super1','Productos Alimenticios')
INSERT INTO [Aplicacion_Productos].[dbo].[Articulos] values('ejemplo','2,000',(SELECT * FROM OPENROWSET(BULK 'C:\Bulk\Progra trabajo\azucar\5.jpg', SINGLE_BLOB) as T1),'super1','Productos Alimenticios')
INSERT INTO [Aplicacion_Productos].[dbo].[Articulos] values('ejemplo','2,000',(SELECT * FROM OPENROWSET(BULK 'C:\Bulk\Progra trabajo\azucar\6.jpg', SINGLE_BLOB) as T1),'super1','Productos Alimenticios')
INSERT INTO [Aplicacion_Productos].[dbo].[Articulos] values('ejemplo','2,000',(SELECT * FROM OPENROWSET(BULK 'C:\Bulk\Progra trabajo\Cafe\2.jpg', SINGLE_BLOB) as T1),'super1','Productos Alimenticios')
INSERT INTO [Aplicacion_Productos].[dbo].[Articulos] values('ejemplo','2,000',(SELECT * FROM OPENROWSET(BULK 'C:\Bulk\Progra trabajo\Cafe\3.jpg', SINGLE_BLOB) as T1),'super1','Productos Alimenticios')
INSERT INTO [Aplicacion_Productos].[dbo].[Articulos] values('ejemplo','2,000',(SELECT * FROM OPENROWSET(BULK 'C:\Bulk\Progra trabajo\Cafe\4.jpg', SINGLE_BLOB) as T1),'super1','Productos Alimenticios')
INSERT INTO [Aplicacion_Productos].[dbo].[Articulos] values('ejemplo','2,000',(SELECT * FROM OPENROWSET(BULK 'C:\Bulk\Progra trabajo\Cafe\5.jpg', SINGLE_BLOB) as T1),'super1','Productos Alimenticios')
INSERT INTO [Aplicacion_Productos].[dbo].[Articulos] values('ejemplo','2,000',(SELECT * FROM OPENROWSET(BULK 'C:\Bulk\Progra trabajo\Cafe\6.jpg', SINGLE_BLOB) as T1),'super1','Productos Alimenticios')
INSERT INTO [Aplicacion_Productos].[dbo].[Articulos] values('ejemplo','2,000',(SELECT * FROM OPENROWSET(BULK 'C:\Bulk\Progra trabajo\Cafe\51QSM56MTGL._AC_UL320_.jpg', SINGLE_BLOB) as T1),'super1','Productos Alimenticios')
INSERT INTO [Aplicacion_Productos].[dbo].[Articulos] values('ejemplo','2,000',(SELECT * FROM OPENROWSET(BULK 'C:\Bulk\Progra trabajo\celulares\1.jpg', SINGLE_BLOB) as T1),'super1','Productos Alimenticios')
INSERT INTO [Aplicacion_Productos].[dbo].[Articulos] values('ejemplo','2,000',(SELECT * FROM OPENROWSET(BULK 'C:\Bulk\Progra trabajo\celulares\2.jpg', SINGLE_BLOB) as T1),'super1','Productos Alimenticios')
INSERT INTO [Aplicacion_Productos].[dbo].[Articulos] values('ejemplo','2,000',(SELECT * FROM OPENROWSET(BULK 'C:\Bulk\Progra trabajo\celulares\3.jpg', SINGLE_BLOB) as T1),'super1','Productos Alimenticios')
INSERT INTO [Aplicacion_Productos].[dbo].[Articulos] values('ejemplo','2,000',(SELECT * FROM OPENROWSET(BULK 'C:\Bulk\Progra trabajo\celulares\4.jpg', SINGLE_BLOB) as T1),'super1','Productos Alimenticios')
INSERT INTO [Aplicacion_Productos].[dbo].[Articulos] values('ejemplo','2,000',(SELECT * FROM OPENROWSET(BULK 'C:\Bulk\Progra trabajo\celulares\5.jpg', SINGLE_BLOB) as T1),'super1','Productos Alimenticios')
INSERT INTO [Aplicacion_Productos].[dbo].[Articulos] values('ejemplo','2,000',(SELECT * FROM OPENROWSET(BULK 'C:\Bulk\Progra trabajo\celulares\6.jpg', SINGLE_BLOB) as T1),'super1','Productos Alimenticios')
INSERT INTO [Aplicacion_Productos].[dbo].[Articulos] values('ejemplo','2,000',(SELECT * FROM OPENROWSET(BULK 'C:\Bulk\Progra trabajo\consolas\1.jpg', SINGLE_BLOB) as T1),'super1','Productos Alimenticios')
INSERT INTO [Aplicacion_Productos].[dbo].[Articulos] values('ejemplo','2,000',(SELECT * FROM OPENROWSET(BULK 'C:\Bulk\Progra trabajo\consolas\2.jpg', SINGLE_BLOB) as T1),'super1','Productos Alimenticios')
INSERT INTO [Aplicacion_Productos].[dbo].[Articulos] values('ejemplo','2,000',(SELECT * FROM OPENROWSET(BULK 'C:\Bulk\Progra trabajo\consolas\3.jpg', SINGLE_BLOB) as T1),'super1','Productos Alimenticios')
INSERT INTO [Aplicacion_Productos].[dbo].[Articulos] values('ejemplo','2,000',(SELECT * FROM OPENROWSET(BULK 'C:\Bulk\Progra trabajo\consolas\4.jpg', SINGLE_BLOB) as T1),'super1','Productos Alimenticios')
INSERT INTO [Aplicacion_Productos].[dbo].[Articulos] values('ejemplo','2,000',(SELECT * FROM OPENROWSET(BULK 'C:\Bulk\Progra trabajo\consolas\5.jpg', SINGLE_BLOB) as T1),'super1','Productos Alimenticios')
INSERT INTO [Aplicacion_Productos].[dbo].[Articulos] values('ejemplo','2,000',(SELECT * FROM OPENROWSET(BULK 'C:\Bulk\Progra trabajo\consolas\6.jpg', SINGLE_BLOB) as T1),'super1','Productos Alimenticios')
INSERT INTO [Aplicacion_Productos].[dbo].[Articulos] values('ejemplo','2,000',(SELECT * FROM OPENROWSET(BULK 'C:\Bulk\Progra trabajo\Desinfectante\1.jpg', SINGLE_BLOB) as T1),'super1','Productos Alimenticios')
INSERT INTO [Aplicacion_Productos].[dbo].[Articulos] values('ejemplo','2,000',(SELECT * FROM OPENROWSET(BULK 'C:\Bulk\Progra trabajo\Desinfectante\2.jpg', SINGLE_BLOB) as T1),'super1','Productos Alimenticios')
INSERT INTO [Aplicacion_Productos].[dbo].[Articulos] values('ejemplo','2,000',(SELECT * FROM OPENROWSET(BULK 'C:\Bulk\Progra trabajo\Desinfectante\3.jpg', SINGLE_BLOB) as T1),'super1','Productos Alimenticios')
INSERT INTO [Aplicacion_Productos].[dbo].[Articulos] values('ejemplo','2,000',(SELECT * FROM OPENROWSET(BULK 'C:\Bulk\Progra trabajo\Desinfectante\5.jpg', SINGLE_BLOB) as T1),'super1','Productos Alimenticios')
INSERT INTO [Aplicacion_Productos].[dbo].[Articulos] values('ejemplo','2,000',(SELECT * FROM OPENROWSET(BULK 'C:\Bulk\Progra trabajo\Desinfectante\6.jpg', SINGLE_BLOB) as T1),'super1','Productos Alimenticios')
INSERT INTO [Aplicacion_Productos].[dbo].[Articulos] values('ejemplo','2,000',(SELECT * FROM OPENROWSET(BULK 'C:\Bulk\Progra trabajo\electrodomesticos\1.jpg', SINGLE_BLOB) as T1),'super1','Productos Alimenticios')
INSERT INTO [Aplicacion_Productos].[dbo].[Articulos] values('ejemplo','2,000',(SELECT * FROM OPENROWSET(BULK 'C:\Bulk\Progra trabajo\electrodomesticos\2.jpg', SINGLE_BLOB) as T1),'super1','Productos Alimenticios')
INSERT INTO [Aplicacion_Productos].[dbo].[Articulos] values('ejemplo','2,000',(SELECT * FROM OPENROWSET(BULK 'C:\Bulk\Progra trabajo\electrodomesticos\3.jpg', SINGLE_BLOB) as T1),'super1','Productos Alimenticios')
INSERT INTO [Aplicacion_Productos].[dbo].[Articulos] values('ejemplo','2,000',(SELECT * FROM OPENROWSET(BULK 'C:\Bulk\Progra trabajo\electrodomesticos\4.jpg', SINGLE_BLOB) as T1),'super1','Productos Alimenticios')
INSERT INTO [Aplicacion_Productos].[dbo].[Articulos] values('ejemplo','2,000',(SELECT * FROM OPENROWSET(BULK 'C:\Bulk\Progra trabajo\electrodomesticos\5.jpg', SINGLE_BLOB) as T1),'super1','Productos Alimenticios')
INSERT INTO [Aplicacion_Productos].[dbo].[Articulos] values('ejemplo','2,000',(SELECT * FROM OPENROWSET(BULK 'C:\Bulk\Progra trabajo\electrodomesticos\6.jpg', SINGLE_BLOB) as T1),'super1','Productos Alimenticios')
INSERT INTO [Aplicacion_Productos].[dbo].[Articulos] values('ejemplo','2,000',(SELECT * FROM OPENROWSET(BULK 'C:\Bulk\Progra trabajo\huevos\1.jpg', SINGLE_BLOB) as T1),'super1','Productos Alimenticios')
INSERT INTO [Aplicacion_Productos].[dbo].[Articulos] values('ejemplo','2,000',(SELECT * FROM OPENROWSET(BULK 'C:\Bulk\Progra trabajo\huevos\2.jpg', SINGLE_BLOB) as T1),'super1','Productos Alimenticios')
INSERT INTO [Aplicacion_Productos].[dbo].[Articulos] values('ejemplo','2,000',(SELECT * FROM OPENROWSET(BULK 'C:\Bulk\Progra trabajo\huevos\3.jpg', SINGLE_BLOB) as T1),'super1','Productos Alimenticios')
INSERT INTO [Aplicacion_Productos].[dbo].[Articulos] values('ejemplo','2,000',(SELECT * FROM OPENROWSET(BULK 'C:\Bulk\Progra trabajo\huevos\4.jpg', SINGLE_BLOB) as T1),'super1','Productos Alimenticios')
INSERT INTO [Aplicacion_Productos].[dbo].[Articulos] values('ejemplo','2,000',(SELECT * FROM OPENROWSET(BULK 'C:\Bulk\Progra trabajo\huevos\5.jpg', SINGLE_BLOB) as T1),'super1','Productos Alimenticios')
INSERT INTO [Aplicacion_Productos].[dbo].[Articulos] values('ejemplo','2,000',(SELECT * FROM OPENROWSET(BULK 'C:\Bulk\Progra trabajo\huevos\6.jpg', SINGLE_BLOB) as T1),'super1','Productos Alimenticios')
INSERT INTO [Aplicacion_Productos].[dbo].[Articulos] values('ejemplo','2,000',(SELECT * FROM OPENROWSET(BULK 'C:\Bulk\Progra trabajo\jabon\1.jpg', SINGLE_BLOB) as T1),'super1','Productos Alimenticios')
INSERT INTO [Aplicacion_Productos].[dbo].[Articulos] values('ejemplo','2,000',(SELECT * FROM OPENROWSET(BULK 'C:\Bulk\Progra trabajo\jabon\2.jpg', SINGLE_BLOB) as T1),'super1','Productos Alimenticios')
INSERT INTO [Aplicacion_Productos].[dbo].[Articulos] values('ejemplo','2,000',(SELECT * FROM OPENROWSET(BULK 'C:\Bulk\Progra trabajo\jabon\3.jpg', SINGLE_BLOB) as T1),'super1','Productos Alimenticios')
INSERT INTO [Aplicacion_Productos].[dbo].[Articulos] values('ejemplo','2,000',(SELECT * FROM OPENROWSET(BULK 'C:\Bulk\Progra trabajo\jabon\4.jpg', SINGLE_BLOB) as T1),'super1','Productos Alimenticios')
INSERT INTO [Aplicacion_Productos].[dbo].[Articulos] values('ejemplo','2,000',(SELECT * FROM OPENROWSET(BULK 'C:\Bulk\Progra trabajo\jabon\5.jpg', SINGLE_BLOB) as T1),'super1','Productos Alimenticios')
INSERT INTO [Aplicacion_Productos].[dbo].[Articulos] values('ejemplo','2,000',(SELECT * FROM OPENROWSET(BULK 'C:\Bulk\Progra trabajo\jabon\6.jpg', SINGLE_BLOB) as T1),'super1','Productos Alimenticios')
INSERT INTO [Aplicacion_Productos].[dbo].[Articulos] values('ejemplo','2,000',(SELECT * FROM OPENROWSET(BULK 'C:\Bulk\Progra trabajo\jamon\1.jpg', SINGLE_BLOB) as T1),'super1','Productos Alimenticios')
INSERT INTO [Aplicacion_Productos].[dbo].[Articulos] values('ejemplo','2,000',(SELECT * FROM OPENROWSET(BULK 'C:\Bulk\Progra trabajo\jamon\2.jpg', SINGLE_BLOB) as T1),'super1','Productos Alimenticios')
INSERT INTO [Aplicacion_Productos].[dbo].[Articulos] values('ejemplo','2,000',(SELECT * FROM OPENROWSET(BULK 'C:\Bulk\Progra trabajo\jamon\3.jpg', SINGLE_BLOB) as T1),'super1','Productos Alimenticios')
INSERT INTO [Aplicacion_Productos].[dbo].[Articulos] values('ejemplo','2,000',(SELECT * FROM OPENROWSET(BULK 'C:\Bulk\Progra trabajo\jamon\4.jpg', SINGLE_BLOB) as T1),'super1','Productos Alimenticios')
INSERT INTO [Aplicacion_Productos].[dbo].[Articulos] values('ejemplo','2,000',(SELECT * FROM OPENROWSET(BULK 'C:\Bulk\Progra trabajo\jamon\5.jpg', SINGLE_BLOB) as T1),'super1','Productos Alimenticios')
INSERT INTO [Aplicacion_Productos].[dbo].[Articulos] values('ejemplo','2,000',(SELECT * FROM OPENROWSET(BULK 'C:\Bulk\Progra trabajo\jamon\6.jpg', SINGLE_BLOB) as T1),'super1','Productos Alimenticios')
INSERT INTO [Aplicacion_Productos].[dbo].[Articulos] values('ejemplo','2,000',(SELECT * FROM OPENROWSET(BULK 'C:\Bulk\Progra trabajo\juegos\1.jpg', SINGLE_BLOB) as T1),'super1','Productos Alimenticios')
INSERT INTO [Aplicacion_Productos].[dbo].[Articulos] values('ejemplo','2,000',(SELECT * FROM OPENROWSET(BULK 'C:\Bulk\Progra trabajo\juegos\2.jpg', SINGLE_BLOB) as T1),'super1','Productos Alimenticios')
INSERT INTO [Aplicacion_Productos].[dbo].[Articulos] values('ejemplo','2,000',(SELECT * FROM OPENROWSET(BULK 'C:\Bulk\Progra trabajo\juegos\3.jpg', SINGLE_BLOB) as T1),'super1','Productos Alimenticios')
INSERT INTO [Aplicacion_Productos].[dbo].[Articulos] values('ejemplo','2,000',(SELECT * FROM OPENROWSET(BULK 'C:\Bulk\Progra trabajo\juegos\4.jpg', SINGLE_BLOB) as T1),'super1','Productos Alimenticios')
INSERT INTO [Aplicacion_Productos].[dbo].[Articulos] values('ejemplo','2,000',(SELECT * FROM OPENROWSET(BULK 'C:\Bulk\Progra trabajo\juegos\5.jpg', SINGLE_BLOB) as T1),'super1','Productos Alimenticios')
INSERT INTO [Aplicacion_Productos].[dbo].[Articulos] values('ejemplo','2,000',(SELECT * FROM OPENROWSET(BULK 'C:\Bulk\Progra trabajo\juegos\6.jpg', SINGLE_BLOB) as T1),'super1','Productos Alimenticios')
INSERT INTO [Aplicacion_Productos].[dbo].[Articulos] values('ejemplo','2,000',(SELECT * FROM OPENROWSET(BULK 'C:\Bulk\Progra trabajo\lactocrema\1.jpg', SINGLE_BLOB) as T1),'super1','Productos Alimenticios')
INSERT INTO [Aplicacion_Productos].[dbo].[Articulos] values('ejemplo','2,000',(SELECT * FROM OPENROWSET(BULK 'C:\Bulk\Progra trabajo\lactocrema\2.jpg', SINGLE_BLOB) as T1),'super1','Productos Alimenticios')
INSERT INTO [Aplicacion_Productos].[dbo].[Articulos] values('ejemplo','2,000',(SELECT * FROM OPENROWSET(BULK 'C:\Bulk\Progra trabajo\lactocrema\3.jpg', SINGLE_BLOB) as T1),'super1','Productos Alimenticios')
INSERT INTO [Aplicacion_Productos].[dbo].[Articulos] values('ejemplo','2,000',(SELECT * FROM OPENROWSET(BULK 'C:\Bulk\Progra trabajo\lactocrema\4.jpg', SINGLE_BLOB) as T1),'super1','Productos Alimenticios')
INSERT INTO [Aplicacion_Productos].[dbo].[Articulos] values('ejemplo','2,000',(SELECT * FROM OPENROWSET(BULK 'C:\Bulk\Progra trabajo\lactocrema\5.jpg', SINGLE_BLOB) as T1),'super1','Productos Alimenticios')
INSERT INTO [Aplicacion_Productos].[dbo].[Articulos] values('ejemplo','2,000',(SELECT * FROM OPENROWSET(BULK 'C:\Bulk\Progra trabajo\lactocrema\6.jpg', SINGLE_BLOB) as T1),'super1','Productos Alimenticios')
INSERT INTO [Aplicacion_Productos].[dbo].[Articulos] values('ejemplo','2,000',(SELECT * FROM OPENROWSET(BULK 'C:\Bulk\Progra trabajo\leche\1.jpg', SINGLE_BLOB) as T1),'super1','Productos Alimenticios')
INSERT INTO [Aplicacion_Productos].[dbo].[Articulos] values('ejemplo','2,000',(SELECT * FROM OPENROWSET(BULK 'C:\Bulk\Progra trabajo\leche\2.jpg', SINGLE_BLOB) as T1),'super1','Productos Alimenticios')
INSERT INTO [Aplicacion_Productos].[dbo].[Articulos] values('ejemplo','2,000',(SELECT * FROM OPENROWSET(BULK 'C:\Bulk\Progra trabajo\leche\3.jpg', SINGLE_BLOB) as T1),'super1','Productos Alimenticios')
INSERT INTO [Aplicacion_Productos].[dbo].[Articulos] values('ejemplo','2,000',(SELECT * FROM OPENROWSET(BULK 'C:\Bulk\Progra trabajo\leche\4.jpg', SINGLE_BLOB) as T1),'super1','Productos Alimenticios')
INSERT INTO [Aplicacion_Productos].[dbo].[Articulos] values('ejemplo','2,000',(SELECT * FROM OPENROWSET(BULK 'C:\Bulk\Progra trabajo\leche\5.jpg', SINGLE_BLOB) as T1),'super1','Productos Alimenticios')
INSERT INTO [Aplicacion_Productos].[dbo].[Articulos] values('ejemplo','2,000',(SELECT * FROM OPENROWSET(BULK 'C:\Bulk\Progra trabajo\leche\6.jpg', SINGLE_BLOB) as T1),'super1','Productos Alimenticios')
INSERT INTO [Aplicacion_Productos].[dbo].[Articulos] values('ejemplo','2,000',(SELECT * FROM OPENROWSET(BULK 'C:\Bulk\Progra trabajo\libros\1.jpg', SINGLE_BLOB) as T1),'super1','Productos Alimenticios')
INSERT INTO [Aplicacion_Productos].[dbo].[Articulos] values('ejemplo','2,000',(SELECT * FROM OPENROWSET(BULK 'C:\Bulk\Progra trabajo\libros\2.jpg', SINGLE_BLOB) as T1),'super1','Productos Alimenticios')
INSERT INTO [Aplicacion_Productos].[dbo].[Articulos] values('ejemplo','2,000',(SELECT * FROM OPENROWSET(BULK 'C:\Bulk\Progra trabajo\libros\3.jpg', SINGLE_BLOB) as T1),'super1','Productos Alimenticios')
INSERT INTO [Aplicacion_Productos].[dbo].[Articulos] values('ejemplo','2,000',(SELECT * FROM OPENROWSET(BULK 'C:\Bulk\Progra trabajo\libros\4.jpg', SINGLE_BLOB) as T1),'super1','Productos Alimenticios')
INSERT INTO [Aplicacion_Productos].[dbo].[Articulos] values('ejemplo','2,000',(SELECT * FROM OPENROWSET(BULK 'C:\Bulk\Progra trabajo\libros\5.jpg', SINGLE_BLOB) as T1),'super1','Productos Alimenticios')
INSERT INTO [Aplicacion_Productos].[dbo].[Articulos] values('ejemplo','2,000',(SELECT * FROM OPENROWSET(BULK 'C:\Bulk\Progra trabajo\libros\6.jpg', SINGLE_BLOB) as T1),'super1','Productos Alimenticios')
INSERT INTO [Aplicacion_Productos].[dbo].[Articulos] values('ejemplo','2,000',(SELECT * FROM OPENROWSET(BULK 'C:\Bulk\Progra trabajo\natilla\1.jpg', SINGLE_BLOB) as T1),'super1','Productos Alimenticios')
INSERT INTO [Aplicacion_Productos].[dbo].[Articulos] values('ejemplo','2,000',(SELECT * FROM OPENROWSET(BULK 'C:\Bulk\Progra trabajo\natilla\2.jpg', SINGLE_BLOB) as T1),'super1','Productos Alimenticios')
INSERT INTO [Aplicacion_Productos].[dbo].[Articulos] values('ejemplo','2,000',(SELECT * FROM OPENROWSET(BULK 'C:\Bulk\Progra trabajo\natilla\3.jpg', SINGLE_BLOB) as T1),'super1','Productos Alimenticios')
INSERT INTO [Aplicacion_Productos].[dbo].[Articulos] values('ejemplo','2,000',(SELECT * FROM OPENROWSET(BULK 'C:\Bulk\Progra trabajo\natilla\4.jpg', SINGLE_BLOB) as T1),'super1','Productos Alimenticios')
INSERT INTO [Aplicacion_Productos].[dbo].[Articulos] values('ejemplo','2,000',(SELECT * FROM OPENROWSET(BULK 'C:\Bulk\Progra trabajo\natilla\5.jpg', SINGLE_BLOB) as T1),'super1','Productos Alimenticios')
INSERT INTO [Aplicacion_Productos].[dbo].[Articulos] values('ejemplo','2,000',(SELECT * FROM OPENROWSET(BULK 'C:\Bulk\Progra trabajo\natilla\6.jpg', SINGLE_BLOB) as T1),'super1','Productos Alimenticios')
INSERT INTO [Aplicacion_Productos].[dbo].[Articulos] values('ejemplo','2,000',(SELECT * FROM OPENROWSET(BULK 'C:\Bulk\Progra trabajo\pan\1.jpg', SINGLE_BLOB) as T1),'super1','Productos Alimenticios')
INSERT INTO [Aplicacion_Productos].[dbo].[Articulos] values('ejemplo','2,000',(SELECT * FROM OPENROWSET(BULK 'C:\Bulk\Progra trabajo\pan\2.jpg', SINGLE_BLOB) as T1),'super1','Productos Alimenticios')
INSERT INTO [Aplicacion_Productos].[dbo].[Articulos] values('ejemplo','2,000',(SELECT * FROM OPENROWSET(BULK 'C:\Bulk\Progra trabajo\pan\3.jpg', SINGLE_BLOB) as T1),'super1','Productos Alimenticios')
INSERT INTO [Aplicacion_Productos].[dbo].[Articulos] values('ejemplo','2,000',(SELECT * FROM OPENROWSET(BULK 'C:\Bulk\Progra trabajo\pan\4.jpg', SINGLE_BLOB) as T1),'super1','Productos Alimenticios')
INSERT INTO [Aplicacion_Productos].[dbo].[Articulos] values('ejemplo','2,000',(SELECT * FROM OPENROWSET(BULK 'C:\Bulk\Progra trabajo\pan\5.jpg', SINGLE_BLOB) as T1),'super1','Productos Alimenticios')
INSERT INTO [Aplicacion_Productos].[dbo].[Articulos] values('ejemplo','2,000',(SELECT * FROM OPENROWSET(BULK 'C:\Bulk\Progra trabajo\pan\6.jpg', SINGLE_BLOB) as T1),'super1','Productos Alimenticios')
INSERT INTO [Aplicacion_Productos].[dbo].[Articulos] values('ejemplo','2,000',(SELECT * FROM OPENROWSET(BULK 'C:\Bulk\Progra trabajo\pasta de dientes\1.jpg', SINGLE_BLOB) as T1),'super1','Productos Alimenticios')
INSERT INTO [Aplicacion_Productos].[dbo].[Articulos] values('ejemplo','2,000',(SELECT * FROM OPENROWSET(BULK 'C:\Bulk\Progra trabajo\pasta de dientes\2.jpg', SINGLE_BLOB) as T1),'super1','Productos Alimenticios')
INSERT INTO [Aplicacion_Productos].[dbo].[Articulos] values('ejemplo','2,000',(SELECT * FROM OPENROWSET(BULK 'C:\Bulk\Progra trabajo\pasta de dientes\3.jpg', SINGLE_BLOB) as T1),'super1','Productos Alimenticios')
INSERT INTO [Aplicacion_Productos].[dbo].[Articulos] values('ejemplo','2,000',(SELECT * FROM OPENROWSET(BULK 'C:\Bulk\Progra trabajo\pasta de dientes\4.jpg', SINGLE_BLOB) as T1),'super1','Productos Alimenticios')
INSERT INTO [Aplicacion_Productos].[dbo].[Articulos] values('ejemplo','2,000',(SELECT * FROM OPENROWSET(BULK 'C:\Bulk\Progra trabajo\pasta de dientes\5.jpg', SINGLE_BLOB) as T1),'super1','Productos Alimenticios')
INSERT INTO [Aplicacion_Productos].[dbo].[Articulos] values('ejemplo','2,000',(SELECT * FROM OPENROWSET(BULK 'C:\Bulk\Progra trabajo\pasta de dientes\6.jpg', SINGLE_BLOB) as T1),'super1','Productos Alimenticios')
INSERT INTO [Aplicacion_Productos].[dbo].[Articulos] values('ejemplo','2,000',(SELECT * FROM OPENROWSET(BULK 'C:\Bulk\Progra trabajo\queso\1.jpg', SINGLE_BLOB) as T1),'super1','Productos Alimenticios')
INSERT INTO [Aplicacion_Productos].[dbo].[Articulos] values('ejemplo','2,000',(SELECT * FROM OPENROWSET(BULK 'C:\Bulk\Progra trabajo\queso\2.jpg', SINGLE_BLOB) as T1),'super1','Productos Alimenticios')
INSERT INTO [Aplicacion_Productos].[dbo].[Articulos] values('ejemplo','2,000',(SELECT * FROM OPENROWSET(BULK 'C:\Bulk\Progra trabajo\queso\3.jpg', SINGLE_BLOB) as T1),'super1','Productos Alimenticios')
INSERT INTO [Aplicacion_Productos].[dbo].[Articulos] values('ejemplo','2,000',(SELECT * FROM OPENROWSET(BULK 'C:\Bulk\Progra trabajo\queso\4.jpg', SINGLE_BLOB) as T1),'super1','Productos Alimenticios')
INSERT INTO [Aplicacion_Productos].[dbo].[Articulos] values('ejemplo','2,000',(SELECT * FROM OPENROWSET(BULK 'C:\Bulk\Progra trabajo\queso\5.jpg', SINGLE_BLOB) as T1),'super1','Productos Alimenticios')
INSERT INTO [Aplicacion_Productos].[dbo].[Articulos] values('ejemplo','2,000',(SELECT * FROM OPENROWSET(BULK 'C:\Bulk\Progra trabajo\queso\6.jpg', SINGLE_BLOB) as T1),'super1','Productos Alimenticios')
INSERT INTO [Aplicacion_Productos].[dbo].[Articulos] values('ejemplo','2,000',(SELECT * FROM OPENROWSET(BULK 'C:\Bulk\Progra trabajo\ropa\1.jpg', SINGLE_BLOB) as T1),'super1','Productos Alimenticios')
INSERT INTO [Aplicacion_Productos].[dbo].[Articulos] values('ejemplo','2,000',(SELECT * FROM OPENROWSET(BULK 'C:\Bulk\Progra trabajo\ropa\2.jpg', SINGLE_BLOB) as T1),'super1','Productos Alimenticios')
INSERT INTO [Aplicacion_Productos].[dbo].[Articulos] values('ejemplo','2,000',(SELECT * FROM OPENROWSET(BULK 'C:\Bulk\Progra trabajo\ropa\3.jpg', SINGLE_BLOB) as T1),'super1','Productos Alimenticios')
INSERT INTO [Aplicacion_Productos].[dbo].[Articulos] values('ejemplo','2,000',(SELECT * FROM OPENROWSET(BULK 'C:\Bulk\Progra trabajo\ropa\4.jpg', SINGLE_BLOB) as T1),'super1','Productos Alimenticios')
INSERT INTO [Aplicacion_Productos].[dbo].[Articulos] values('ejemplo','2,000',(SELECT * FROM OPENROWSET(BULK 'C:\Bulk\Progra trabajo\ropa\5.jpg', SINGLE_BLOB) as T1),'super1','Productos Alimenticios')
INSERT INTO [Aplicacion_Productos].[dbo].[Articulos] values('ejemplo','2,000',(SELECT * FROM OPENROWSET(BULK 'C:\Bulk\Progra trabajo\ropa\6.jpg', SINGLE_BLOB) as T1),'super1','Productos Alimenticios')
INSERT INTO [Aplicacion_Productos].[dbo].[Articulos] values('ejemplo','2,000',(SELECT * FROM OPENROWSET(BULK 'C:\Bulk\Progra trabajo\sal\1.jpg', SINGLE_BLOB) as T1),'super1','Productos Alimenticios')
INSERT INTO [Aplicacion_Productos].[dbo].[Articulos] values('ejemplo','2,000',(SELECT * FROM OPENROWSET(BULK 'C:\Bulk\Progra trabajo\sal\2.jpg', SINGLE_BLOB) as T1),'super1','Productos Alimenticios')
INSERT INTO [Aplicacion_Productos].[dbo].[Articulos] values('ejemplo','2,000',(SELECT * FROM OPENROWSET(BULK 'C:\Bulk\Progra trabajo\sal\3.jpg', SINGLE_BLOB) as T1),'super1','Productos Alimenticios')
INSERT INTO [Aplicacion_Productos].[dbo].[Articulos] values('ejemplo','2,000',(SELECT * FROM OPENROWSET(BULK 'C:\Bulk\Progra trabajo\sal\4.jpg', SINGLE_BLOB) as T1),'super1','Productos Alimenticios')
INSERT INTO [Aplicacion_Productos].[dbo].[Articulos] values('ejemplo','2,000',(SELECT * FROM OPENROWSET(BULK 'C:\Bulk\Progra trabajo\sal\5.jpg', SINGLE_BLOB) as T1),'super1','Productos Alimenticios')
INSERT INTO [Aplicacion_Productos].[dbo].[Articulos] values('ejemplo','2,000',(SELECT * FROM OPENROWSET(BULK 'C:\Bulk\Progra trabajo\sal\6.jpg', SINGLE_BLOB) as T1),'super1','Productos Alimenticios')







